#!/usr/bin/env python3
"""Interactive setup — run this first.

Asks for your API credentials and the destination channel, then logs in your
userbot account (phone -> OTP code -> 2FA password if set) and writes .env.

Run:  python setup.py
"""
from __future__ import annotations

import asyncio
from getpass import getpass
from pathlib import Path

from telethon import TelegramClient

BASE = Path(__file__).resolve().parent
ENV_PATH = BASE / ".env"
SESSION = str(BASE / "userbot")


def ask(prompt: str, default: str | None = None, secret: bool = False) -> str:
    label = prompt + (f" [{default}]" if default else "") + ": "
    while True:
        value = (getpass(label) if secret else input(label)).strip()
        if not value and default is not None:
            return default
        if value:
            return value
        print("  (required)")


def write_env(values: dict[str, str]) -> None:
    lines = ["# Generated by setup.py - do not commit this file.\n"]
    lines += [f"{k}={v}\n" for k, v in values.items()]
    ENV_PATH.write_text("".join(lines))
    print(f"\nWrote {ENV_PATH}")


async def main() -> None:
    print("=" * 60)
    print(" ZIP -> channel userbot — setup")
    print(" API_ID / API_HASH come from https://my.telegram.org")
    print("=" * 60)

    api_id = ask("API_ID")
    api_hash = ask("API_HASH", secret=True)
    post_channel = ask("POST_CHANNEL (@username, -100... id, or invite link)")
    owners = ask("OWNERS - extra user ids allowed to send zips (comma sep)",
                 default="")

    print("\n" + "-" * 60)
    print(" Logging in your userbot account.")
    print(" Telegram sends a login code to your app; enter it when asked.")
    print("-" * 60)
    phone = ask("Phone number (with country code, e.g. +15551234567)")

    client = TelegramClient(SESSION, int(api_id), api_hash)
    await client.start(phone=lambda: phone)  # prompts OTP + 2FA itself
    me = await client.get_me()
    print(f"Logged in as {me.first_name} (id {me.id}).")
    await client.disconnect()

    write_env({
        "API_ID": api_id,
        "API_HASH": api_hash,
        "POST_CHANNEL": post_channel,
        "OWNERS": owners,
        "ALBUM_SIZE": "9",
        "SEND_DELAY": "2",
    })

    print("\nAll set. Start it with:\n  python userbot.py")
    print("Then send a .zip to this account's DM / Saved Messages.")
    print("\nMake sure this account can POST in the target channel.")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nSetup cancelled.")
